Add Travis & Doxygen
adafruit/Adafruit_APDS9960 pull request #15
Opened 2019-01-04 15:04 UTC by szymonkaliski

Ping @ladyada :)

2019-01-04 15:51 UTC, ladyada requested changes

2019-01-04 15:51 UTC, ladyada commented on README.md
> +# Adafruit APDS9960 Library [![Build Status](https://travis-ci.org/adafruit/Adafruit_APDS9960_Library.svg?branch=master)](https://travis-ci.org/adafruit/Adafruit_APDS9960_Library)
change to travis-ci.com please :)

2019-01-04 15:51 UTC, ladyada commented on Adafruit_APDS9960.cpp
> + *  @brief  Reads 32 bytes from specified register
bits not bytes

2019-01-04 15:51 UTC, ladyada commented on Adafruit_APDS9960.cpp
> + *  @brief  Reads 8 bytes from specified register
bits

2019-01-04 15:51 UTC, ladyada commented on Adafruit_APDS9960.cpp
> + *  @brief  Reads 16 bytes from specified register
ditto

2019-01-04 15:51 UTC, ladyada commented on Adafruit_APDS9960.cpp
> + *  @brief  Reads 16 bytes from specified register
ditto

2019-01-04 18:36 UTC, ladyada approved these changes

2019-01-04 18:36 UTC, merged

2019-01-04 18:37 UTC, ladyada commented
shoot merged but the travis link is wrong - please fix

should be https://travis-ci.com/adafruit/Adafruit_APDS9960

2019-01-05 09:03 UTC, szymonkaliski commented
→ https://github.com/adafruit/Adafruit_APDS9960/pull/16 :)